### ISSUE TITLE
NUMAMPS

### ISSUE THREAD

**Issue by esalvolucas** [KeckObservatoryArchive/data-evaluation-and-processing#304]
How does IDL get any numbers greater than 2, based on numamps.pro? Currently getting 4

**Comment by jmader** [comment]
NUMAMPS that you're seeing is an LRIS written keyword.  Apparently this keyword has no meaning:

https://www2.keck.hawaii.edu/koa/public/keywords/lrisKeywords.php?keyword=NUMAMPS

Your set_numamps should be get_numamps.  It will just return the number based on LRIS (AMPMODE) or LRISBLUE (AMPLIST).  Then, in set_sig2nois, you will use self.get_numamps instead of using the keyword value.
